services:
  gateway:
    image: nesbal/dotnet-gateway:latest
    container_name: gateway
    ports:
      - "${GATEWAY_PORT:-8080}:80"
    depends_on:
      - authservice
      - productservice
      - logservice
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AuthService__BaseUrl=http://authservice
      - ProductService__BaseUrl=http://productservice
      - LogService__BaseUrl=http://logservice

  authservice:
    image: nesbal/dotnet-authservice:latest
    container_name: authservice
    expose:
      - "80"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./data/auth:/app/data

  productservice:
    image: nesbal/dotnet-productservice:latest
    container_name: productservice
    expose:
      - "80"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - redis
    volumes:
      - ./data/product:/app/data

  logservice:
    image: nesbal/dotnet-logservice:latest
    container_name: logservice
    expose:
      - "80"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./data/log:/app/data

  redis:
    image: redis:7
    container_name: redis
    expose:
      - "6379"
