name: .NET Microservices CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore NsbCaseStudy.sln

      - name: Build
        run: dotnet build NsbCaseStudy.sln --no-restore

      - name: Test
        run: dotnet test NsbCaseStudy.sln --no-build || echo "No tests found"